using System.Collections.Generic;

namespace OpenAIToolkit
{
    /// <summary>
    ///     Create edit response
    ///     <a href="https://platform.openai.com/docs/api-reference/edits/create">See more</a>
    /// </summary>
    public class CreateEditResponse : BaseResponse
    {
        /// <summary>
        ///     Represents the time when the response was created. The value is expressed in Unix timestamp format.
        /// </summary>
        public int Created { get; internal set; }

        /// <summary>
        ///     The list of choices generated by the request.
        /// </summary>
        public List<Choice> Choices { get; internal set; }

        /// <summary>
        ///     The usage information for the request.
        /// </summary>
        public Usage Usage { get; internal set; }
    }
}