namespace OpenAIToolkit
{
    /// <summary>
    ///     The usage information of a model.
    /// </summary>
    public class Usage
    {
        /// <summary>
        ///     Number of tokens used for prompting the model.
        /// </summary>
        public int PromptTokens { get; internal set; }

        /// <summary>
        ///     Number of tokens generated by the model.
        /// </summary>
        public int CompletionTokens { get; internal set; }

        /// <summary>
        ///     The total number of tokens used in interaction with the model.
        /// </summary>
        public int TotalTokens { get; internal set; }
    }
}